### PR TITLE
Implemented Google Chromecast SDK on project.

### PR DESCRIPTION
**Pull request by BorisEsanu818**
Require code review and QA

### CODE REVIEW

**Comment by andyzheng547** [comment]
@BorisEsanu818 We are not able to connect to any Chromecast devices when testing the branch. We loaded the app on an iPhone 6 and aren't able to find any Chromecast devices on the same wifi. Can you let us know how you are testing the feature?

There are also a few things that should be cleaned up. 
1. Please remove the hardcoded image url for **Zype/ViewController/VideoDetailViewController.m, line 2056**. The selected video should already have a thumbnail url as an attribute and we should not be using a test image.
2. Can you please move some variables into the **Zype/Utilities/ZypeCommon.h** file. This is the file used to store all the configuration and feature flags. There are a few variables that are used for configuring the feature and would be easier to find and update inside the configuration file:
- **kReceiverAppID** and ** kDebugLoggingEnabled** inside **Zype/AppDelegate.m**
- ** IS_CAST_DEBUG_MODE** inside **Zype/ViewController/VideoDetailViewController.m**

**Comment by BorisEsanu818** [comment]
@andyzheng547 
Did you set up cast device correctly? (maybe you can check / sync cast device with Google home app).  If cast device is ok, you can find cast icon on VideoDetailView Screen (upper right corner). 
And I will update code you mentioned.

**Comment by andyzheng547** [comment]
@BorisEsanu818 Yes the same phone casts to our Nexus Player on other apps. I can see the icon that asks me to select a device. The only device shown is a "Nearby Device" and when I follow the flow it asks for a PIN but the device I am trying to cast to does not prompt me with a PIN.

**Comment by BorisEsanu818** [comment]
@andyzheng547  please check cast with I last updated code. (and if device shown is "Nearby Device", try restart device and connect.)

**Comment by andyzheng547** [comment]
@BorisEsanu818 While testing we encountered 2 issues. Can you take a look and see if they can be replicated?

1. If you cast to the Chromecast while the player is playing, the Chromecast tries to play but the time is stuck on 0:01 and does not finish loading. The Chromecast does not seek the time that the player was at before the user selects the Chromecast player. The buttons to jump forward or backward 30 seconds need to be clicked before the Chromecast seeks a time and plays.
2. If you cast to the Chromecast while the player is paused, the view in the app says that there is no media available to cast to the device.

**Comment by BorisEsanu818** [comment]
@andyzheng547 I did not encounter this issue and it works well on my side.(there is no openssl change on source update history.)

**Comment by andyzheng547** [comment]
@BorisEsanu818 I was doing some branch cleanup and deleted the autoplay branch since autoplay was merged into the master in [pull request #45 ](https://github.com/zype/zype-ios/pull/45). I did not realize that it would close this pull request.

Can you open another pull request based off the master branch?

**Pull request closed without merging**
